/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Breadcrumbs: typeof import('./../components/common/breadcrumbs/index.vue')['default']
    ConfigDrawer: typeof import('./../components/common/config-drawer/index.vue')['default']
    Fade: typeof import('./../components/animates/fade.vue')['default']
    FixedFooter: typeof import('./../components/layouts/fixed-footer.vue')['default']
    FullScreen: typeof import('./../components/header/full-screen/index.vue')['default']
    GlobalSearch: typeof import('./../components/header/global-search/index.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    LayoutWithHeader: typeof import('./../components/layouts/layout-with-header.vue')['default']
    Loading: typeof import('./../components/header/loading/index.vue')['default']
    MenuCollapse: typeof import('./../components/header/menu-collapse/index.vue')['default']
    Motion: typeof import('motion/vue')['Motion']
    NormalTab: typeof import('./../components/common/nav-tabs/normal-tab/index.vue')['default']
    Refresh: typeof import('./../components/header/refresh/index.vue')['default']
    RegularLayout: typeof import('./../components/layouts/regular-layout.vue')['default']
    ScaleDown: typeof import('./../components/animates/scale-down.vue')['default']
    ScaleUp: typeof import('./../components/animates/scale-up.vue')['default']
    SimpleTab: typeof import('./../components/common/nav-tabs/simple-tab/index.vue')['default']
    SlideLeft: typeof import('./../components/animates/slide-left.vue')['default']
    SlideRight: typeof import('./../components/animates/slide-right.vue')['default']
    SwitchLanguage: typeof import('./../components/common/switch-language/index.vue')['default']
    ToggleTheme: typeof import('./../components/header/toggle-theme/index.vue')['default']
  }
}
