version: '1.0'
name: pipeline-20230905
displayName: pipeline-20230905
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
  pr:
    branches:
      precise:
        - main
stages:
  - name: stage-14ec6808
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-ab2659f7
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@k8s
        name: deploy_k8s
        displayName: K8S部署
        version: v1.16.4
        certificate: efd4a620-2db3-013c-7c32-6e8bea218bd0
        namespace: default
        yaml: ./deployment.yaml
        isReplace: false
        skiptls: false
        params: null
        notify: []
        strategy:
          retry: '0'
